BEGIN;

-- The public schema
create schema api;

-- Internal schema for TimescaleDB
create schema internal;

-- Per-network schema
create schema IF not exists testnet;
create schema IF not exists mainnet;
create schema IF not exists common;

-- Anonymous role for web access
create role web_anon nologin;
grant usage on schema api to web_anon;

-- Trusted user for web access
create role authenticator noinherit nologin;
grant web_anon to authenticator;

-- Dedicated role for writing to the database
create role writer nologin;
grant usage on schema api to writer;
grant writer to authenticator;

-- Excluded address table
CREATE TABLE excluded_addresses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value TEXT NOT NULL UNIQUE
);

-- Return all excluded addresses as an array
CREATE OR REPLACE FUNCTION api.get_excluded_addresses()
RETURNS TEXT[] AS $$
  SELECT array_agg(value) FROM excluded_addresses;
$$ LANGUAGE sql STABLE;

-- Add a new excluded address to the table
CREATE OR REPLACE FUNCTION api.add_excluded_address(_value TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO excluded_addresses(value)
  VALUES (_value)
  ON CONFLICT (value) DO NOTHING;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- Remove an excluded address from the table
CREATE OR REPLACE FUNCTION api.rm_excluded_address(_value TEXT)
RETURNS VOID AS $$
BEGIN
  DELETE FROM excluded_addresses
  WHERE value = _value;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- Web anon should not be able to execute these functions
REVOKE EXECUTE ON FUNCTION api.add_excluded_address(TEXT) FROM PUBLIC, web_anon;
REVOKE EXECUTE ON FUNCTION api.rm_excluded_address(TEXT) FROM PUBLIC, web_anon;

-- Grant execute permissions to the writer role
GRANT EXECUTE ON FUNCTION api.add_excluded_address(TEXT) TO writer;
GRANT EXECUTE ON FUNCTION api.rm_excluded_address(TEXT) TO writer;

CREATE OR REPLACE FUNCTION api.get_all_latest_common_metrics()
  RETURNS TABLE(
    table_name  TEXT,
    "timestamp" TIMESTAMPTZ,
    "value"     TEXT
  )
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = common, internal, public
AS $$
DECLARE
  sql TEXT;
BEGIN
  SELECT string_agg(
           format(
             '(SELECT %L AS table_name, time, value::TEXT FROM common.%I ORDER BY time DESC LIMIT 1)',
             t.table_name,
             t.table_name
           ),
           E'\nUNION ALL\n'
         )
    INTO sql
    FROM information_schema.tables AS t
   WHERE t.table_schema = 'common'
     AND t.table_type   = 'BASE TABLE';

  RETURN QUERY EXECUTE sql;
END;
$$;

GRANT EXECUTE
  ON FUNCTION api.get_all_latest_common_metrics()
  TO web_anon;

COMMIT;