BEGIN;

-- Anonymous role for web access
create role web_anon noinherit nologin;
GRANT USAGE ON SCHEMA public TO web_anon;

-- Revoke all privileges on all tables in the public schema from public
REVOKE ALL
  ON ALL TABLES IN SCHEMA public
  FROM PUBLIC;

-- Grant SELECT on all tables in the public schema to web_anon
GRANT SELECT
  ON ALL TABLES IN SCHEMA public
  TO web_anon;

-- Grant SELECT on future tables in the public schema to web_anon
ALTER DEFAULT PRIVILEGES
  IN SCHEMA public
  GRANT SELECT ON TABLES
  TO web_anon;

CREATE TABLE excluded_addresses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value TEXT NOT NULL UNIQUE
);

CREATE OR REPLACE FUNCTION get_excluded_addresses()
RETURNS TEXT[] AS $$
  SELECT array_agg(value) FROM excluded_addresses;
$$ LANGUAGE sql STABLE;

create role authenticator noinherit nologin;
grant web_anon to authenticator;

-- Trusted user
create role writer nologin;
grant writer to authenticator;

grant usage on schema public to writer;
grant all on public.excluded_addresses to writer;

COMMIT;
