BEGIN;

CREATE TABLE IF NOT EXISTS internal.excluded_addresses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value TEXT NOT NULL UNIQUE
);
GRANT SELECT, INSERT, DELETE ON internal.excluded_addresses TO writer;
GRANT SELECT ON internal.excluded_addresses TO web_anon;

-- Return all excluded addresses as an array
CREATE OR REPLACE FUNCTION api.get_excluded_addresses()
RETURNS SETOF TEXT
SECURITY DEFINER
SET search_path = api, internal, public
AS $$
  SELECT value FROM internal.excluded_addresses;
$$ LANGUAGE sql STABLE;
GRANT EXECUTE ON FUNCTION api.get_excluded_addresses TO web_anon;

-- Add a new excluded address to the table
CREATE OR REPLACE FUNCTION api.add_excluded_address(_value TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO internal.excluded_addresses(value)
  VALUES (_value)
  ON CONFLICT (value) DO NOTHING;
END;
$$ LANGUAGE plpgsql VOLATILE STRICT;

-- Remove an excluded address from the table
CREATE OR REPLACE FUNCTION api.rm_excluded_address(_value TEXT)
RETURNS VOID AS $$
BEGIN
  DELETE FROM internal.excluded_addresses
  WHERE value = _value;
END;
$$ LANGUAGE plpgsql VOLATILE STRICT;

-- Web anon should not be able to execute these functions
REVOKE EXECUTE ON FUNCTION api.add_excluded_address(TEXT) FROM PUBLIC, web_anon;
REVOKE EXECUTE ON FUNCTION api.rm_excluded_address(TEXT) FROM PUBLIC, web_anon;

-- Grant execute permissions to the writer role
GRANT EXECUTE ON FUNCTION api.add_excluded_address(TEXT) TO writer;
GRANT EXECUTE ON FUNCTION api.rm_excluded_address(TEXT) TO writer;

COMMIT;
